### ISSUE TITLE
Unkown PCM cards

### ISSUE THREAD

**Issue by pasimko** [fabiofalci/sconsify#64] opened 2017-01-03 02:03 UTC
$ ./sconsify
    <username>
    <password>
Then I get these errors:

    ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
    ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
    ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
    ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
    Cannot connect to server socket err = No such file or directory
    Cannot connect to server request channel
    jack server is not running or cannot be started
    JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
    JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock

**Comment by fabiofalci** [comment] 2017-01-03 09:49
@pasimko sconsify is getting stuck at the playlist load. Not sure yet why. I'll need some time to find out.

**Comment by pasimko** [comment] 2017-01-06 01:48
Unfortunately, my premium ran out yesterday, so I'm not going to be able to
test it.

**Comment by fabiofalci** [comment] 2017-01-06 09:39
Ok, no problems, thank you for reporting. 
Will close the issue for now then.

**Closed by fabiofalci** 2017-01-06 09:39 UTC

**Comment by kflak** [comment] 2019-02-07 13:47
Getting the same issue:
```
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 933
```
Running Arch Linux with alsa-pulseaudio-jack bridge enabled. Tried both vanilla and web-api versions.

**Comment by fabiofalci** [comment] 2019-02-07 14:44
@kflak can you check if this fixes your issue? https://github.com/fabiofalci/sconsify/issues/108

**Comment by kflak** [comment] 2019-02-08 08:10
@fabiofalci OK, looking into it a bit more indepth now, and realizing that part of the problem is mostly my stupidity and the fact that I hadn't created any playlists in spotify prior to testing out sconsify. When I did this, the messages still come up, but the application is loaded successfully, and is able to play back the playlists, but *not on my external soundcard!* So it seems there is still some voodoo going on under the hood here.
